### ISSUE TITLE
more EIS new keywords. Deleting LROC placeholders

### ISSUE THREAD

**Issue by RayEspiritu** [pds-data-dictionaries/ldd-clipper#13]
add more EIS keywords. Delete the placeholder keywords copied from LROC

**Comment by thareUSGS** [comment]
@RayEspiritu Are you planning to attempt this? I wasn't sure if I missed a message with the updates.

**Comment by RayEspiritu** [comment]
Hi Trent,

Yes, I’m still working on it. I’ll send an email to you and Paul once I’m done with the updates to the branch.

Ray

From: Trent Hare ***@***.***>
Reply-To: pds-data-dictionaries/ldd-clipper ***@***.***>
Date: Tuesday, February 27, 2024 at 6:17 PM
To: pds-data-dictionaries/ldd-clipper ***@***.***>
Cc: "Espiritu, Raymond C." ***@***.***>, Mention ***@***.***>
Subject: [EXT] Re: [pds-data-dictionaries/ldd-clipper] more EIS new keywords. Deleting LROC placeholders (Issue #13)

APL external email warning: Verify sender ***@***.*** before clicking links or attachments




@RayEspiritu<https://github.com/RayEspiritu> Are you planning to attempt this? I wasn't sure if I missed a message with the updates.

**Comment by RayEspiritu** [comment]
I let my local branch from before the most recent merge lag behind the version on the git repo. I have to retype 5 EIS keywords back into the branch.

Ray

From: "Espiritu, Raymond C." ***@***.***>
Date: Tuesday, February 27, 2024 at 6:26 PM
To: pds-data-dictionaries/ldd-clipper ***@***.***>, pds-data-dictionaries/ldd-clipper ***@***.***>
Cc: Mention ***@***.***>
Subject: Re: [EXT] Re: [pds-data-dictionaries/ldd-clipper] more EIS new keywords. Deleting LROC placeholders (Issue #13)

Hi Trent,

Yes, I’m still working on it. I’ll send an email to you and Paul once I’m done with the updates to the branch.

Ray

From: Trent Hare ***@***.***>
Reply-To: pds-data-dictionaries/ldd-clipper ***@***.***>
Date: Tuesday, February 27, 2024 at 6:17 PM
To: pds-data-dictionaries/ldd-clipper ***@***.***>
Cc: "Espiritu, Raymond C." ***@***.***>, Mention ***@***.***>
Subject: [EXT] Re: [pds-data-dictionaries/ldd-clipper] more EIS new keywords. Deleting LROC placeholders (Issue #13)

APL external email warning: Verify sender ***@***.*** before clicking links or attachments




@RayEspiritu<https://github.com/RayEspiritu> Are you planning to attempt this? I wasn't sure if I missed a message with the updates.
